name: CI/CD template for Studi live on Heroku PaaS

on:
  push:
    branches: ["**"] #sur chaque branch

jobs: 
  sonar-analysis:
    name: sonar analysis
    runs-on: ubuntu-24.04
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth : 0 #conservation de l'historique git 
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: sonarcloud scan
        uses: SonarSource/sonarqube-scan-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #Gérer par github
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  
  deploy-heroku:
    # on execute le jobs "deploy-heroku" que si la branch est main
    if: github.ref == 'refs/heads/main'
    needs: sonar-analysis # attend que le job sonar-analysis soit terminé
    runs-on: ubuntu-24.04
    environment: prod
    
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ vars.HEROKU_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to heroku docker registry
        run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      - name: build docker image
        run: docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .

      - name: push docker image
        run: docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: deploy image to HEROKU_APP_NAME
        run : | 
          curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -d '{
            "updates": [
              { 
                "type": "web",
                "docker_image": "'"$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})"'"
              }
            ]
          }' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY"
      
      - name: Ensure Dynos Scaled 
        run: | 
          curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation/web \
            -d '{"quantity": 1}' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3" \
            -H "Authorization: Bearer $HEROKU_API_KEY"

